const mongoose = require('mongoose')
mongoose.Promise = require('bluebird')
const Book = require('../models/Book')
const bookData = require('./data/bookData')
const {dbURI} = require('../config/environment')

mongoose.connect(dbURI, {useNewUrlParser: true })
  .then(() => mongoose.connection.db.dropDatabase())
  .then(() => Book.create(bookData))
  .then(() => console.log('Successfully seeded!'))
  .catch((err) => console.log(err))
  .finally(() => mongoose.connection.close())
